::batch script to print an image as text-image
::https://www.text-image.com/index.html 

@echo off

::set the title
title LINKIN PARK

::set the text color to green and background to black
color 0A
	
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhNMNhhdNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyo/-..oMN+....-/oymNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNds/..:+shmNm+..hmhs+-../smNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+.`:smNMMNNm+..dNNNMMNms:`-odNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo.`/dNMNNNNNd+..hNmmNNNNNMNd/`-omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd:`-hNNNNNNNmd+..hmddsdmNNNNNNNh../dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMd:`:mMNNNNmmdd+..hdhd/.odmmmNNNNMm-`:dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMm/.-NMNNNNmmdh+..hdyd/...ohdmmNNNNMm../mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMNy.`hMNNNNmmdh+..hhsh/.-y..ohdmmNNNNMh`.hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMm+.-MNNNNmmdh+..hhoh/.-hhy..ohdmmNNNNM..omMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMd:./MNNNmmdd+..hhoy/`-hoohy..ohdmmNNNM:./dMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMm/.:MNNNmmdo..hhsh/.-ho+oshy..odmmNNNM-./mMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMNo.`NMNNNmo..hdyh+.-hsossyydy..smNNNMN`.smMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMd.`oMMNmo..+yyy+..oyssssyyyy+..smNMM+`-dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.`yMmy:::::-..-:::::::::::::::hmMy`.ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMms.`sNmmmmmd/..yhhhhhhhdddddmmmmms`.smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy-`/dNNNN+..ymmmmmmmmmNNNNNNNd:`-ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd+../hm+..yNNNNmmNNNNNNMMNh/.-+dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNho-.-..yNNMNNNNNNMNNmy+-.-ohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmy+:yNm/+oossoo/:-.-:oymNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMNho+/::::/+osydNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

::stopping the tab close >null is used for avoid printing "Press any key to continue ..." message
pause >nul